{
    "name": "Techzilla Global Compliance",
    "summary": "Globalization and UAE compliance foundation",
    "version": "17.0.1.0.0",
    "category": "Accounting/Accounting",
    "author": "Techzilla",
    "license": "LGPL-3",
    "depends": [
        "base",
        "account",
        "contacts",
        "crm",
        "hr_expense",
        "tz_api_gateway",
        "tz_accounting_extension",
        "tz_commission",
        "tz_property_inventory",
        "tz_payroll",
        "tz_site_visit",
        "tz_call_center",
        "tz_whatsapp",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/res_company_views.xml",
        "views/res_partner_views.xml",
        "views/res_config_settings_views.xml",
        "views/account_move_views.xml",
        "data/compliance_defaults.xml",
    ],
    "installable": True,
    "application": False,
}
