{
    "name": "TZ Dashboard",
    "version": "1.0.0",
    "summary": "Management dashboard for Techzilla CRM",
    "category": "Sales/CRM",
    "author": "Techzilla Global",
    "depends": [
        "crm",
        "tz_crm_base",
        "tz_realestate_leads",
        "tz_site_visit",
        "tz_commission"
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/dashboard_views.xml",
 	"views/crm_lead_conversion_views.xml",
	"views/agent_performance_views.xml",
        "views/menu.xml",
	"views/res_users_views.xml",
	"security/followup_activity_rules.xml",
	"views/followup_activity_views.xml",
	"views/supervisor_dashboard_views.xml",
	"data/followup_cron.xml",
	"views/res_config_settings_views.xml",
	"views/sla_breach_queue_views.xml",
	"views/team_followup_monitor_views.xml",
	"views/rescue_sla_queue_views.xml",
	"views/lead_history_views.xml",
	"views/res_config_settings_views.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}