{
    "name": "TZ Role Module Access",
    "version": "17.0.2.0.0",
    "summary": "Configure menu/module/submodule access per CRM role",
    "category": "Security",
    "author": "Techzilla",
    "license": "LGPL-3",
    "depends": [
        "base",
        "crm",
        "contacts",
        "hr",
        "hr_attendance",
        "hr_expense",
        "account",
        "tz_crm_base",
        "tz_realestate_leads",
        "tz_property_inventory",
        "tz_site_visit",
        "tz_call_center",
        "tz_whatsapp",
        "tz_api_gateway",
        "tz_lead_assignment",
        "tz_commission",
        "tz_accounting_extension",
        "tz_dashboard",
        "tz_hr_extension",
        "tz_live_tracking",
        "tz_attendance_geo",
        "tz_expense_extension",
        "tz_payroll",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/module_feature_data.xml",
        "views/role_module_access_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
