from . import res_company
from . import res_partner
from . import res_config_settings
from . import account_move
from . import crm_lead
from . import property_inventory
from . import commission
from . import hr_expense
from . import tz_payroll
from . import api_log
from . import activity_integrity
